name: hikmah_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  adhan: any
  cloud_firestore: any
  file_picker: any
  firebase_auth: any
  firebase_core: any
  flutter_qiblah: any
  geocoding: any
  geolocator: any
  http: any
  image_picker: any
  intl: any
  permission_handler: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
